#!/usr/bin/env php
<?php

require_once __DIR__ . '/bootstrap_events.php';
require_once __DIR__ . '/../app/services/MailhogEmailService.php';

if (!EVENTS_ENABLED) {
    echo "Events are disabled. Set EVENTS_ENABLED=true to run consumers.\n";
    exit(0);
}

$db = Database::getInstance()->getConnection();
$consumerName = 'email_consumer';
$emailService = new MailhogEmailService();

$connection = createRabbitConnection();
$channel = $connection->channel();
$channel->exchange_declare(RABBITMQ_EXCHANGE, RABBITMQ_EXCHANGE_TYPE, false, true, false);
declareDlx($channel);

$queueArgs = queueArguments();
$channel->queue_declare(RABBITMQ_EMAIL_QUEUE, false, true, false, false, false, $queueArgs);

$routingKeys = array_map(
    static fn(string $eventName): string => strtolower(str_replace('_', '.', $eventName)),
    DomainEvents::all()
);

foreach ($routingKeys as $routingKey) {
    $channel->queue_bind(RABBITMQ_EMAIL_QUEUE, RABBITMQ_EXCHANGE, $routingKey);
}

if (RABBITMQ_DLX_EXCHANGE !== '') {
    $dlq = RABBITMQ_DLQ_PREFIX . '.email';
    $channel->queue_declare($dlq, false, true, false, false);
    $channel->queue_bind($dlq, RABBITMQ_DLX_EXCHANGE, '#');
}

$channel->basic_qos(null, 20, null);

echo "[email] Waiting for messages on queue '" . RABBITMQ_EMAIL_QUEUE . "'...\n";

$processedInsert = $db->prepare('INSERT INTO processed_events (consumer_name, event_uuid) VALUES (?, ?)');
$processedCheck = $db->prepare('SELECT COUNT(*) FROM processed_events WHERE consumer_name = ? AND event_uuid = ?');

$getUserByIdStmt = $db->prepare(
    "SELECT id, full_name, email
     FROM users
     WHERE id = ?
       AND is_active = 1
       AND email IS NOT NULL
       AND TRIM(email) <> ''
     LIMIT 1"
);

$getUsersByRoleStmt = $db->prepare(
    "SELECT id, full_name, email
     FROM users
     WHERE role = ?
       AND is_active = 1
       AND email IS NOT NULL
       AND TRIM(email) <> ''
     ORDER BY id ASC"
);

$supervisorsBySubmittedTechStmt = $db->prepare(
    "SELECT DISTINCT fta.assigned_by
     FROM fault_ticket_assignments fta
     INNER JOIN users supervisor ON supervisor.id = fta.assigned_by
     WHERE fta.fault_ticket_id = ?
       AND fta.assigned_to = ?
       AND fta.status = 'Active'
       AND supervisor.role = 'Supervisor'
     ORDER BY fta.assigned_at DESC"
);

$supervisorsByTicketStmt = $db->prepare(
    "SELECT DISTINCT fta.assigned_by
     FROM fault_ticket_assignments fta
     INNER JOIN users supervisor ON supervisor.id = fta.assigned_by
     WHERE fta.fault_ticket_id = ?
       AND fta.status = 'Active'
       AND supervisor.role = 'Supervisor'
     ORDER BY fta.assigned_at DESC"
);

$fetchUserById = function (int $userId) use ($getUserByIdStmt): ?array {
    if ($userId <= 0) {
        return null;
    }

    $getUserByIdStmt->execute([$userId]);
    $user = $getUserByIdStmt->fetch(PDO::FETCH_ASSOC);
    return is_array($user) ? $user : null;
};

$fetchUsersByRole = function (string $role) use ($getUsersByRoleStmt): array {
    $getUsersByRoleStmt->execute([$role]);
    $users = $getUsersByRoleStmt->fetchAll(PDO::FETCH_ASSOC);
    return is_array($users) ? $users : [];
};

$buildBody = function (string $headline, string $message): string {
    $safeHeadline = htmlspecialchars($headline, ENT_QUOTES, 'UTF-8');
    $safeMessage = nl2br(htmlspecialchars($message, ENT_QUOTES, 'UTF-8'));

    return "
    <html>
    <body style='font-family: Arial, sans-serif; background: #f7f9fb; margin: 0; padding: 20px;'>
        <div style='max-width: 620px; margin: 0 auto; background: #ffffff; border: 1px solid #e5e7eb; border-radius: 8px; overflow: hidden;'>
            <div style='background: #2563eb; color: #ffffff; padding: 18px 24px;'>
                <h2 style='margin: 0; font-size: 20px;'>AssetCare360 Event Notification</h2>
            </div>
            <div style='padding: 20px 24px;'>
                <h3 style='margin-top: 0; color: #1f2937;'>{$safeHeadline}</h3>
                <p style='line-height: 1.6; color: #374151;'>{$safeMessage}</p>
                <p style='margin-top: 20px; color: #6b7280; font-size: 13px;'>
                    This message was generated by the RabbitMQ email consumer.
                </p>
            </div>
        </div>
    </body>
    </html>";
};

$buildEmailRecords = function (array $event) use (
    $fetchUserById,
    $fetchUsersByRole,
    $supervisorsBySubmittedTechStmt,
    $supervisorsByTicketStmt,
    $buildBody
): array {
    $data = $event['data'] ?? [];
    $records = [];
    $seenEmails = [];

    $appendRecord = function (array $user, string $subject, string $headline, string $message) use (&$records, &$seenEmails, $buildBody): void {
        $email = strtolower(trim((string)($user['email'] ?? '')));
        if ($email === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) {
            return;
        }

        if (isset($seenEmails[$email])) {
            return;
        }

        $seenEmails[$email] = true;
        $records[] = [
            'to_email' => $email,
            'to_name' => trim((string)($user['full_name'] ?? '')),
            'subject' => $subject,
            'body_html' => $buildBody($headline, $message),
        ];
    };

    $addUserById = function (?int $userId, string $subject, string $headline, string $message) use ($fetchUserById, $appendRecord): void {
        if ($userId === null || $userId <= 0) {
            return;
        }

        $user = $fetchUserById($userId);
        if ($user) {
            $appendRecord($user, $subject, $headline, $message);
        }
    };

    $addRoleUsers = function (string $role, string $subject, string $headline, string $message) use ($fetchUsersByRole, $appendRecord): void {
        $users = $fetchUsersByRole($role);
        foreach ($users as $user) {
            $appendRecord($user, $subject, $headline, $message);
        }
    };

    switch ($event['event']) {
        case DomainEvents::USER_ACCOUNT_CREATED:
            $recipientEmail = strtolower(trim((string)($data['email'] ?? '')));
            if ($recipientEmail === '' || !filter_var($recipientEmail, FILTER_VALIDATE_EMAIL)) {
                break;
            }

            $subject = 'Your AssetCare360 account details';
            $headline = 'Welcome to AssetCare360';
            $loginId = (string)($data['employee_id'] ?? 'N/A');
            $temporaryPassword = (string)($data['temporary_password'] ?? 'N/A');
            $role = (string)($data['role'] ?? 'N/A');
            $loginUrl = (string)($data['login_url'] ?? (rtrim(FRONTEND_BASE_URL, '/') . '/auth/login.html'));

            $message = "Your account has been created by the system administrator.\n"
                . "\nLogin URL: {$loginUrl}"
                . "\nLogin ID: {$loginId}"
                . "\nTemporary Password: {$temporaryPassword}"
                . "\nAssigned Role: {$role}"
                . "\n\nFor security, you are required to change your password after first login.";

            if (!isset($seenEmails[$recipientEmail])) {
                $seenEmails[$recipientEmail] = true;
                $records[] = [
                    'to_email' => $recipientEmail,
                    'to_name' => trim((string)($data['full_name'] ?? '')),
                    'subject' => $subject,
                    'body_html' => $buildBody($headline, $message),
                ];
            }
            break;

        case DomainEvents::FAULT_TICKET_CREATED:
            $ticketId = $data['ticket_id'] ?? (($data['ticket_db_id'] ?? null) ? ('#' . $data['ticket_db_id']) : 'Unknown');
            $subject = 'New fault ticket created: ' . $ticketId;
            $headline = 'Fault Ticket Created';
            $message = "A new fault ticket {$ticketId} has been created and is awaiting assignment.";
            $addRoleUsers('Supervisor', $subject, $headline, $message);
            break;

        case DomainEvents::FAULT_TICKET_ASSIGNED:
            $ticketId = $data['ticket_id'] ?? (($data['ticket_db_id'] ?? null) ? ('#' . $data['ticket_db_id']) : 'Unknown');
            $subject = 'Ticket assigned: ' . $ticketId;
            $headline = 'Ticket Assignment';
            $message = "Ticket {$ticketId} has been assigned to you. Please review and proceed.";
            $userIds = isset($data['technician_user_ids']) && is_array($data['technician_user_ids']) ? $data['technician_user_ids'] : [];
            foreach ($userIds as $userId) {
                $addUserById((int)$userId, $subject, $headline, $message);
            }
            break;

        case DomainEvents::BUDGET_REPORT_CREATED:
            $approvalRole = strtolower(str_replace(' ', '_', trim((string)($data['approval_role'] ?? 'Supervisor'))));
            $reportId = (string)($data['report_id'] ?? 'N/A');
            $subject = 'Budget review required: ' . $reportId;
            $headline = 'Budget Approval Required';
            $message = 'A budget report is waiting for your approval.';

            // Maintenance Manager can approve all budget requests, so always notify this role.
            $addRoleUsers('Maintenance Manager', $subject, $headline, $message);

            if ($approvalRole === 'supervisor') {
                $ticketId = isset($data['fault_ticket_id']) ? (int)$data['fault_ticket_id'] : 0;
                $submittedBy = isset($data['submitted_by']) ? (int)$data['submitted_by'] : null;
                $supervisorIds = [];

                try {
                    if ($ticketId > 0 && $submittedBy !== null && $submittedBy > 0) {
                        $supervisorsBySubmittedTechStmt->execute([$ticketId, $submittedBy]);
                        $supervisorIds = array_values(array_unique(array_map(
                            static fn(array $row): int => (int)$row['assigned_by'],
                            $supervisorsBySubmittedTechStmt->fetchAll(PDO::FETCH_ASSOC)
                        )));
                    }

                    if ($ticketId > 0 && empty($supervisorIds)) {
                        $supervisorsByTicketStmt->execute([$ticketId]);
                        $supervisorIds = array_values(array_unique(array_map(
                            static fn(array $row): int => (int)$row['assigned_by'],
                            $supervisorsByTicketStmt->fetchAll(PDO::FETCH_ASSOC)
                        )));
                    }
                } catch (Throwable $routingError) {
                    error_log('[email] Supervisor routing lookup failed: ' . $routingError->getMessage());
                    $supervisorIds = [];
                }

                foreach ($supervisorIds as $supervisorId) {
                    $addUserById((int)$supervisorId, $subject, $headline, $message);
                }

                if (empty($records)) {
                    $addRoleUsers('Supervisor', $subject, $headline, $message);
                }

                break;
            }
            break;

        case DomainEvents::BUDGET_REPORT_REVIEWED:
            $status = strtoupper((string)($data['status'] ?? 'PENDING'));
            $reportId = (string)($data['report_id'] ?? 'N/A');
            $subject = 'Budget decision received: ' . $reportId;
            $headline = 'Budget Decision: ' . $status;
            $message = 'Your submitted budget report has been reviewed.';
            $submittedBy = isset($data['submitted_by']) ? (int)$data['submitted_by'] : null;
            $addUserById($submittedBy, $subject, $headline, $message);
            break;

        case DomainEvents::SPARE_PART_REQUEST_CREATED:
            $requestId = (string)($data['request_id'] ?? $data['request_db_id'] ?? 'N/A');
            $subject = 'Spare-part request pending review: ' . $requestId;
            $headline = 'Spare-Part Request Submitted';
            $message = 'A new spare-part request has been submitted and needs review.';
            $addRoleUsers('Inventory Manager', $subject, $headline, $message);
            break;

        case DomainEvents::SPARE_PART_REQUEST_APPROVED:
        case DomainEvents::SPARE_PART_REQUEST_REJECTED:
            $status = $event['event'] === DomainEvents::SPARE_PART_REQUEST_APPROVED ? 'APPROVED' : 'REJECTED';
            $requestId = (string)($data['request_id'] ?? $data['request_db_id'] ?? 'N/A');
            $subject = 'Spare-part request ' . strtolower($status) . ': ' . $requestId;
            $headline = 'Spare-Part Request ' . $status;
            $message = 'Your spare-part request has been ' . strtolower($status) . '.';
            $requestedBy = isset($data['requested_by']) ? (int)$data['requested_by'] : null;
            $addUserById($requestedBy, $subject, $headline, $message);
            break;

        case DomainEvents::ASSET_MACHINE_CREATED:
            $assetLabel = (string)($data['machine_id'] ?? $data['machine_name'] ?? 'N/A');
            $subject = 'New machine asset created: ' . $assetLabel;
            $headline = 'Machine Asset Created';
            $message = 'A new machine asset has been added to the system.';
            $addRoleUsers('Admin', $subject, $headline, $message);
            break;

        case DomainEvents::ASSET_VEHICLE_CREATED:
            $assetLabel = (string)($data['vehicle_id'] ?? $data['vehicle_name'] ?? 'N/A');
            $subject = 'New vehicle asset created: ' . $assetLabel;
            $headline = 'Vehicle Asset Created';
            $message = 'A new vehicle asset has been added to the system.';
            $addRoleUsers('Admin', $subject, $headline, $message);
            break;

        case DomainEvents::ASSET_SERVICE_DUE_SOON:
            $assetCode = (string)($data['asset_code'] ?? $data['asset_id'] ?? 'N/A');
            $dueDate = (string)($data['due_date'] ?? 'soon');
            $subject = 'Asset service due soon: ' . $assetCode;
            $headline = 'Service Due Reminder';
            $message = "Asset {$assetCode} requires service on {$dueDate}.";
            $addRoleUsers('Inventory Manager', $subject, $headline, $message);
            break;
    }

    return $records;
};

$callback = function (\PhpAmqpLib\Message\AMQPMessage $msg) use ($consumerName, $processedCheck, $processedInsert, $buildEmailRecords, $emailService) {
    try {
        $payload = json_decode($msg->body, true);
        if (!is_array($payload)) {
            throw new RuntimeException('Invalid JSON payload');
        }

        $validation = EventEnvelope::validate($payload);
        if (!$validation['valid']) {
            throw new RuntimeException('Invalid envelope: ' . $validation['message']);
        }

        $eventUuid = $payload['id'];

        $processedCheck->execute([$consumerName, $eventUuid]);
        if ((int)$processedCheck->fetchColumn() > 0) {
            $msg->ack();
            return;
        }

        $records = $buildEmailRecords($payload);

        foreach ($records as $record) {
            $sent = $emailService->send(
                $record['to_email'],
                $record['subject'],
                $record['body_html'],
                $record['to_name']
            );

            if (!$sent) {
                throw new RuntimeException('Failed to send email to ' . $record['to_email']);
            }
        }

        if (empty($records)) {
            error_log('[email] No eligible recipients for event: ' . $payload['event']);
        }

        $processedInsert->execute([$consumerName, $eventUuid]);
        $msg->ack();
    } catch (Throwable $e) {
        error_log('[email] Consume error: ' . $e->getMessage());
        $msg->nack(false, true);
    }
};

$channel->basic_consume(RABBITMQ_EMAIL_QUEUE, '', false, false, false, false, $callback);

while ($channel->is_consuming()) {
    $channel->wait();
}
